# Generated by Django 5.0.6 on 2024-12-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default=9876543210, max_length=10),
            preserve_default=False,
        ),
    ]
